Install JFrog CLI for all CCI images
conan-io/conan-docker-tools pull request #243
Opened 2021-01-19 18:42 UTC by uilianries

As Conan Center Index is doing internal changes, JFrog CLI will be required.

I didn't add for x86 images because they are optional and not used by CCI.

- [ ] Refer to the issue that supports this Pull Request.
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [ ] I've read the [Contributing guide](https://github.com/conan-io/conan-docker-tools/blob/master/.github/CONTRIBUTING.md).
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008) style guides for Python code.
- [ ] I've followed the [Best Practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) guides for Dockerfile.

2021-01-19 19:12 UTC, jgsogo requested changes
We should better use documented install command: https://jfrog.com/getcli/ 

```
wget -qO - https://releases.jfrog.io/artifactory/api/gpg/key/public | sudo apt-key add -;
echo "deb https://releases.jfrog.io/artifactory/jfrog-debs xenial contrib" | sudo tee -a /etc/apt/sources.list;
sudo apt update;
sudo apt install -y jfrog-cli;
```

2021-01-19 19:29 UTC, Croydon commented
It only provides debs for bionic, eon, focal and xenial, so it won't work for all images

2021-01-19 19:32 UTC, uilianries commented
Yes, that's why I downloaded directly. 

The script provided by Jfrog runs wget, but downloads to the current folder.
Basically, I'm running GetCi.sh from JFrog

2021-01-19 21:33 UTC, jgsogo reviewed
👍

2021-01-20 09:14 UTC, danimtb approved these changes

2021-01-20 12:01 UTC, merged