Install libc++-11 with clang-11
conan-io/conan-docker-tools pull request #252
Opened 2021-03-01 22:56 UTC by Woazim

Changelog: Fix: This is to install libc++-11 instead of default one (6 or 7, very old)

- [x] Refer to the issue that supports this Pull Request.
- [x] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [x] I've read the [Contributing guide](https://github.com/conan-io/conan-docker-tools/blob/master/.github/CONTRIBUTING.md).
- [x] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008) style guides for Python code.
- [x] I've followed the [Best Practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) guides for Dockerfile.

fixes #251

2021-03-02 12:15 UTC, uilianries requested changes
Thank you for your contribution!

Unfortunately we can't accept this change. Updating libstdc++ or libstdc++11 will break official packages in Conan Center. If you really need a newer version, we can do it locally.

We will provide new Docker images soon, including newer libc version. Thus, your hotfix is still a valid idea, but it will be included for other Docker images.

2021-03-02 12:23 UTC, uilianries commented
Looking https://github.com/conan-io/conan-center-index/pull/4630, it seems like no clang-11 package has been generated yet. Thus, it's possible to accept your PR.

2021-03-02 12:24 UTC, uilianries approved these changes
LGTM, it fixes https://github.com/conan-io/conan-center-index/pull/4630

2021-03-03 01:49 UTC, Croydon approved these changes

2021-03-04 12:31 UTC, jgsogo requested changes
Need to understand the implications. If we upgrade this library to version `libc++11`, then the binaries compiled using this new version can run with the old one? Does every consumer need to upgrade to `libc++11` in order to run the binaries compiled with it?

That would be a blocker, as `libc++` will be the default for many users.

2021-03-04 13:42 UTC, Woazim commented
I think there is a misunderstanding. clang-11 should come with libcxx-11. But this lib and its ABI must be installed separately as it's noticed in official clang page [here](https://apt.llvm.org/#install_stable) (see 'To install all key packages' / '# Clang and co'. If you just install libcxx through `apt-get install libcxx-dev` you install a very old version of libcxx (version 6). This version does not support modern C++ and is not what clang-11 users expect.

By the way, this [official LLVM link](https://libcxx.llvm.org/docs/DesignDocs/ABIVersioning.html) explains that "Libc++ aims to preserve stable ABI to avoid subtle bugs when code built to the old ABI is linked with the code build to the new ABI". So it should not be a problem to correct this, but, I agree with you, it can not be sure.

Finally, this Dockerfile is not consistent with the one for clang-10 (which is good). You'll see on [these lines](https://github.com/conan-io/conan-docker-tools/blob/058db05060cfedc3f78e42320a0980e2df56d4cf/clang_10/Dockerfile#L37-L39) that libcxx-**10**-dev is installed (not libcxx-dev).

I'm sorry, but there is clearly a problem with this clang-11 installation. I don't know the right way to correct this, but it must be corrected. From your side, is it possible to rebuild all clang-11/libcxx in conan-center recipes to avoid side effects?

2021-03-04 14:42 UTC, jgsogo commented
We will be using the same docker image for all the compilers (we are proposing Ubuntu 16.04) to ensure all the binaries have the same and a lower enough `glibc` version (this is convenient for the `build_requirements`). All current images will be deprecated in favor of those ones.

The issue would be, for example, if we build some tool using clang-11 (with `libc++11`) and then we need to run that tool on the images we use for all the `gcc` and `clang` compilers... will it run?

2021-03-04 16:30 UTC, uilianries commented
I didn't find any clear information about libc++ backward compatibility, but Marshall Clow (libc++ owner) [answered](https://stackoverflow.com/questions/66477097/is-libc-backward-compatible-with-older-versions) that it should work.

2021-03-04 17:06 UTC, Woazim commented
I've run a little test: I build ImaGL and its test program with clang-11, libc++-11. I ran it on a fresh Ubuntu 16.04 with default libc++ (v3.7) without any problem.

2021-03-05 11:35 UTC, jgsogo commented
There are several questions that came to me related to this issue and they will help us a lot with other ongoing efforts as well.

 * The plan is to move to the same base docker image for all the Linux compilers, ATM the chosen one is `Ubuntu 16.04` (LTS).  We still don't know if this scenario is possible, there are some questions that need answers:
    * Can we get to run all the compilers (from GCC 4.9 to GCC 10, and clang 3.9 to 11) in this version of Ubuntu? We will need to compile from sources some of them... (versions TBD https://github.com/conan-io/conan-center-index/issues/4761)
    * We would need to compile some missing packages too: is `libc++11` available for `16.04`? can we build it from sources?

    Maybe we realize we cannot use the same base image for all the compilers and it will totally change the perspective from where to look at this issue.

 * We need to understand why the `libc++` package now is called `libc++11`, surely there is some ABI break. We just need to confirm it, it is ok to write a demo app to demonstrate it. **It won't be a blocker**, but we need to know the implications of the decision. 
   * Can `LIBCXX_ABI_VERSION` help us? Can we use version 11 but use `LIBCXX_ABI_VERSION` to target old ABIs and still get all the modern C++ features?

 * If ABI is incompatible, should we consider it as a new entry to `compiler.libcxx` for Clang compilers and add `libc++11` to the list?

2021-03-05 12:16 UTC, uilianries commented
I would to continue this discussion about unifying or not at #205, which is the appropriated issue. This PR is related to clang fix.

2021-03-05 14:36 UTC, jgsogo commented
I think I did some fundamental failure above. The runtime packages are `libc++abi1-11` and `libc++1-11` which (if I'm reading the names properly) are compatible for all versions from `1` to `11` (Ubuntu 20.04). So, they must be able to run any binary compiled up to `libc++-11-dev`.

So, this is not about installing `libc++-11` as the runtime, as a different package from `libc++`, this is only about upgrading the `dev` library... and we will need to be sure that we can install `libc++abi1-11` in the base image we want to use.

The question, for this issue, is just: are there `libc++abi1-11`/`libc++1-11` packages available for Ubuntu 16.04? If not, can we build them from sources?

Sorry for the misunderstanding.

2021-03-05 23:45 UTC, Woazim commented
> The question, for this issue, is just: **are there `libc++abi1-11`/`libc++1-11` packages available for Ubuntu 16.04? If not, can we build them from sources?**

Short answer: yes

Long answer: yes, following these instructions from a docker ubuntu:xenial image:
``` sh
apt-get update
apt-get install -y wget software-properties-common apt-transport-https
wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -
add-apt-repository "deb http://apt.llvm.org/xenial/   llvm-toolchain-xenial-11  main"
apt-get update
apt-get install -y libc++1-11 libc++abi1-11
```

By the way, libc++1-12 and libc++abi1-12 from clang-12 are also installable with this script.

2021-06-09 08:28 UTC, jgsogo commented
Please, have a look to this approach: https://github.com/conan-io/conan-docker-tools/pull/267

2021-10-02 07:20 UTC, ericLemanissier commented
This can now be closed

2021-10-02 14:13 UTC, closed without merging