adds support for GCC 11
conan-io/conan-docker-tools pull request #260
Opened 2021-05-15 14:54 UTC by fpelliccioni

Changelog: (Feature | Fix | Bugfix): Describe here your pull request

- [ ] Refer to the issue that supports this Pull Request.
- [ ] If the issue has missing info, explain the purpose/use case/pain/need that covers this Pull Request.
- [ ] I've read the [Contributing guide](https://github.com/conan-io/conan-docker-tools/blob/master/.github/CONTRIBUTING.md).
- [ ] I've followed the [PEP8](https://www.python.org/dev/peps/pep-0008) style guides for Python code.
- [ ] I've followed the [Best Practices](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/) guides for Dockerfile.

2021-05-15 19:22 UTC, Croydon requested changes

2021-05-15 19:22 UTC, Croydon commented on gcc_11/Dockerfile
> +       g++-${GCC_VERSION} \
This image was not build as you have not added it to the `docker-compose.yml` file.

`gcc-11` does not exist for Ubuntu Focal

2021-05-31 19:39 UTC, uilianries commented
Please, consider https://github.com/fpelliccioni/conan-docker-tools/pull/1

This PR is outdated and Conan target version need to be updated.

2021-05-31 20:08 UTC, fpelliccioni commented
> Please, consider [fpelliccioni#1](https://github.com/fpelliccioni/conan-docker-tools/pull/1)
> 
> This PR is outdated and Conan target version need to be updated.

merged, thanks!

2021-05-31 21:51 UTC, merged

2021-05-31 21:51 UTC, uilianries commented
Thank you!